# Generated by Django 5.1.5 on 2025-02-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='date_created',
        ),
    ]
